### ISSUE TITLE
Tilde in Sign Column

### ISSUE THREAD

**Issue by Caddy121** [OXY2DEV/foldtext.nvim#2]
How do I get rid of the tildes in the sign column? I was able to set fillchars = ' ' before but that doesn't work when using the foldtext plugin.

**Comment by OXY2DEV** [comment]
You mean something like this?

![Screenshot_2024-09-17-11-49-00-421_com termux-edit](https://github.com/user-attachments/assets/3b6cfa79-b261-400c-912f-dab5e3e9426f)

**Comment by OXY2DEV** [comment]
Also,
You should be doing something like this.

```lua
vim.o.fillchars = "eob: ,fold: ";
```

And not
```lua
vim.o.fillchars = ' ';
```

**Comment by Caddy121** [comment]
> Also, You should be doing something like this.
> 
> ```lua
> vim.o.fillchars = "eob: ,fold: ";
> ```
> 
> And not
> 
> ```lua
> vim.o.fillchars = ' ';
> ```

You're right. I do have "eob" in my options but not "fold". Thanks for your help, and thanks for the plugin!
